name: Self service performance test
on: 
    
  workflow_dispatch:
    inputs:
      scriptname:
        description: 'Nama Script'     
        required: true
        default: '.js'
      vus:
        description: 'VUS'
        required: true
        default: '1'
      stages:
        description: 'Timeout'
        required: true
        default: '5000'
        
        

jobs:
 change-and-run:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Change VUs
        run: | 
            echo $GITHUB_REF
            sed 's/$GITHUB_REF.4/1/'k6_scriptt.js
      - name: Run local k6 test with docker
        uses: k6io/action@v0.1
        with:
            filename : k6_scriptt1.js
