name: Self service performance test
on: 
  workflow_dispatch:
    inputs:
      scriptname:
        description: 'Nama Script'     
        required: true
        default: ''
      vus:
        description: 'VUS'
        required: true
        default: '1'
      stages:
        description: 'Timeout'
        required: true
        default: '5000'

jobs:
 change-and-run:
    runs-on: ubuntu-latest
#     container: docker://loadimpact/k6:latest
    env:
        FILE_NAME: k6_script.js
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
#       - name: Create File
#         uses: finnp/create-file-action@1.0.0
      - name: Change VUs
        run: | 
           sed -i -e 's/VU = 4/${{github.event.inputs.vus}}/g' -e 's/timeout: 5000/timeout: ${{github.event.inputs.stages}}/g' ${{github.event.inputs.scriptname}} > ${FILE_NAME}            
      - name: Run local k6 test with docker
        uses: k6io/action@v0.1
        with:
            filename : ${FILE_NAME}
