name: Self service performance test
on: 
  workflow_dispatch:
    inputs:
      scriptname:
        description: 'Nama Script'     
        required: true
        default: '.js'
      vus:
        description: 'VUS'
        required: true
        default: '1'
      stages:
        description: 'Timeout'
        required: true
        default: '5000'
      base_url:
        description: 'URL'
        required: true
        default: 'test-api.k6.io'

jobs:
 change-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Change script
        run: | 
           sed -i -e 's/VU = 4/VU = ${{github.event.inputs.vus}}/g' -e 's/timeout: 5000/timeout: ${{github.event.inputs.stages}}/g' -e 's/test-api.k6.io/${{github.event.inputs.base_url}}/g' ${{github.event.inputs.scriptname}}     
           cat ${{github.event.inputs.scriptname}}
        
      - name: Run local k6 test with docker
        uses: k6io/action@v0.1
        with:
            path: |
            filename: ${{github.event.inputs.scriptname}} 
